### ISSUE TITLE
Pwease add build instruction

### ISSUE THREAD

**Issue by banhbaochi3n** [hoangtan2002/yuuko#1]
I am a noob, pwease gimme the exe I dont know how to build this pwogwam. Much thx UwU

![yui_mad](https://github.com/hoangtan2002/yuuko/assets/35733326/83e54a99-82a7-4339-92a5-a9328a2ebec3)

**Comment by hoangtan2002** [comment]
Coming soon

**Comment by hoangtan2002** [comment]
build instruction added via commit 752ecda, close this fr
