### ISSUE TITLE
this is bloat

### ISSUE THREAD

**Issue by banhbaochi3n** [hoangtan2002/yuuko#2]
i dont wan meson so bloat i want only gcc this repo sucks ass the code smells pls rewrite everything and use only gcc much thx UwU

https://github.com/hoangtan2002/yuuko/assets/35733326/2fcfa024-23a5-4806-b2f1-f9719cc7eba6

**Comment by hoangtan2002** [comment]
> Gcc is used by default on most distro anyway and i dont think it is bloat so close this fr
