### ISSUE TITLE
this does not build saar

### ISSUE THREAD

**Issue by banhbaochi3n** [hoangtan2002/yuuko#3]
idk why didnt this buidl saar pls help kind saar i am noob dont tell me to read error logs much thx kind saar

![image](https://github.com/hoangtan2002/yuuko/assets/35733326/2c2f74c0-26f6-4164-8e85-c5997ad80d70)

![image](https://github.com/hoangtan2002/yuuko/assets/35733326/fe71cf59-b348-405e-80b9-61e783939d0a)

**Comment by hoangtan2002** [comment]
msvc is not supported for now, please use msys2-mingw, that is the only thing i can test

**Comment by banhbaochi3n** [comment]
ok kind saar

**Comment by hoangtan2002** [comment]
close it rn
